# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Elias Strehle
title: Software Engineer and Researcher
email: strehle.elias@gmail.com
# website: www.github.com/estrehle

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  estrehle
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: elias-strehle-474a11128
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-4351-7865

# Additional icon links
# additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I studied business administration and financial mathematics, completing my PhD in mathematics in 2017.
  Since then I have worked in IT: as a Python data engineer, a blockchain researcher and a TypeScript full-stack developer.

  My passion is to make complicated things work.
  I enjoy teaching myself and others complex concepts, from mathematics to machine learning and software architecture (which is why I loved academic research).
  And I enjoy building things that put these concepts to work and make a difference in real life (which is why I left academic research).

content:
  - title: IT Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-center
        title: Fullstack Development
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
          # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I taught myself TypeScript/JavaScript in early 2021.
          Since then I have built several prototype full-stack applications.
          My current default tech stack comprises Angular and AWS Amplify for frontend and Nest.js, MySQL, Docker and AWS Lightsail for backend, both hosted and deployed from GitHub.
          The applications I built for my employers are proprietary, but I have published a showcase server-to-server chat application [here](https://github.com/estrehle/webchat).

          As much as I enjoy programming, I view it as a tool to accomplish things that are useful to actual humans.
          My best moments as a developer were not spent in front of my IDE but in conversations with smart and passionate people.
          Next to my programming work I have tried to teach myself a little software architecture (particularly domain-driven design), requirements engineering and project management.
      - layout: top-center
        title: Decentralized Data Exchanges
        description: |
          Over the last two years, much of my work has revolved around decentralized data exchanges.
          Here, "decentralized" means that data is not stored and controlled by one party;
          instead, each piece of data is stored and controlled by its respective owner or creator.
          Decentralized data exchanges promise high degrees of privacy and data sovereignty, but come with unique challenges in the areas of privacy, consistency and interoperability.

          I had the opportunity to dive into this topic during my work as a blockchain researcher and also in my current position as a software engineer.
          Some of my outputs are publicly available, including a [blog post on blockchain's confidentiality issues](https://www.blockchainresearchlab.org/2020/12/11/enterprise-dlt-the-leaky-trust-machine-2/)
          and a [working paper introducing a privacy-preserving decentralized data exchange](https://www.blockchainresearchlab.org/wp-content/uploads/2020/05/BRL-Working-Paper-No-18-DibiChain.pdf).
          Currently I am contributing to the [BloG³ research project](https://www.blog3.de/) (link in German), where we are trying to build a decentralized data exchange for patients' medical data using the [Hyperledger Aries](https://www.hyperledger.org/use/aries) ecosystem.

          If you want to talk about decentralized data exchanges or have an idea of how we could collaborate, please let me know!

# Footer
footer_show_references: true
references_title: Built with Matt Sproogen's Modern Resume Theme (https://github.com/sproogen/modern-resume-theme)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
