# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Elias Strehle
title: Software Engineer and Researcher
email: strehle.elias@gmail.com

darkmode: false

# Social links
github_username:  estrehle
linkedin_username: elias-strehle-474a11128
orcid_username: 0000-0002-4351-7865

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I studied business administration and financial mathematics, completing my PhD in mathematics in 2017.
  Since then I have worked in IT as a Python data engineer, blockchain researcher and TypeScript full-stack developer.

  My passion is to make complicated things work.
  I enjoy teaching myself and others complex concepts, from mathematics to machine learning and software architecture (which is why I loved academic research).
  And I enjoy building things that put these concepts to work and make a difference in real life (which is why I left academic research).

content:
  - title: IT Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fullstack Development
        description: | # this will include new lines to allow paragraphs
          I taught myself TypeScript/JavaScript in early 2021.
          Since then I have built several prototypes of full-stack applications.
          My current default tech stack comprises the [Angular](https://angular.io/) and [Nest.js](https://nestjs.com/) frameworks, MySQL, Docker, GitHub and AWS (EC2, RDS, Amplify, Lightsail).
          
          The applications I built for my employers are proprietary, but I have published a showcase [server-to-server chat application](https://github.com/estrehle/webchat).

          As much as I enjoy programming, I view it as a tool to accomplish things that are useful.
          My best moments as a developer were not spent in front of my IDE but in conversations with smart and passionate people.
      - layout: left
        title: Decentralized Data Exchanges
        description: |
          Much of my recent work has revolved around decentralized data exchanges.
          These are computer networks where data is stored and controlled by its owners and not by a central intermediary.

          My personal focus within this area has been on the (in-)applicability of blockchain technology and [self-sovereign identity](https://en.wikipedia.org/wiki/Self-sovereign_identity) frameworks.
          Some of my outputs are publicly available, including a [blog post](https://www.blockchainresearchlab.org/2020/12/11/enterprise-dlt-the-leaky-trust-machine-2/) on blockchain's confidentiality issues
          and a [working paper](https://www.blockchainresearchlab.org/wp-content/uploads/2020/05/BRL-Working-Paper-No-18-DibiChain.pdf) sketching a privacy-preserving decentralized data exchange.
          
          Currently I am part of the [BloG³ research project](https://www.blog3.de/) (link in German) which aims to give patients autonomy over their own medical data.
          My contribution to the project includes architecting and implementing a decentralized data exchange built on top of the [Hyperledger Aries](https://www.hyperledger.org/use/aries) toolkit.
#       - layout: left
#         title: Data Engineering and Machine Learning
#         description: |
          
# Footer
footer_show_references: true
references_title: Built with Matt Sproogen's Modern Resume Theme (https://github.com/sproogen/modern-resume-theme)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
